name: Deploying GSSAR
'on':
  push:
    branches:
      - main
      - ft/**
      - bug/**
      - hotfix/**
      - release/**
  pull_request:
    branches:
      - main
      - ft/**
      - bug/**
      - hotfix/**
      - release/**
jobs:
  get-branch-name:
    runs-on: ubuntu-latest
    outputs:
      branch: '${{ steps.extract_branch.outputs.branch }}'
    steps:
      - uses: actions/checkout@v2
      - name: Extract branch name
        shell: bash
        run: 'echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"'
        id: extract_branch
  job2:
    runs-on: ubuntu-latest
    needs: get-branch-name
    steps:
      - run: 'echo ${{needs.get-branch-name.outputs.branch}}'
